{{- if eq .Values.co "openshift" }}
kind: SecurityContextConstraints
{{- $majorVersion := index .Values.coVersion 0 }}
{{- if eq $majorVersion '4' }}
apiVersion: security.openshift.io/v1
{{- else if eq $majorVersion '3' }}
apiVersion: v1
{{- end }}
metadata:
  name: scc-csi-driver
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "csi-driver.fullname" . }}-controller-account
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "csi-driver.fullname" . }}-node-account
{{- end }}
