dist: trusty

git:
  depth: false

branches:
  only:
    - master

jobs:
  include:
    - stage: check
      script: ./build.sh
      if: type = pull_request
    - stage: deploy
      script: ./build.sh deploy
      if: type = push

