apiVersion: v2
appVersion: v5.3.0-rc13
dependencies:
- name: zookeeper-operator
  repository: http://iomesh.com/charts
  version: 0.2.15
- name: hostpath-provisioner
  repository: http://iomesh.com/charts
  version: 0.5.3
- condition: openebs-ndm.enabled
  name: openebs-ndm
  repository: http://iomesh.com/charts
  version: 1.8.0
- name: csi-driver
  repository: http://iomesh.com/charts
  version: 2.6.0
- name: blockdevice-monitor
  repository: http://iomesh.com/charts
  version: 0.1.0
- condition: iomesh-localpv-manager.enabled
  name: iomesh-localpv-manager
  repository: http://iomesh.com/charts
  version: 0.1.0
description: Install all IOMesh components
name: iomesh
type: application
version: v1.0.1
