apiVersion: v2
name: juicefs
description: A Helm chart for JuiceFS CSI Driver
type: application
version: 0.9.2
appVersion: 0.13.2
kubeVersion: ">=1.14.0-0"
home: https://github.com/juicedata/juicefs
sources:
  - https://github.com/juicedata/juicefs
icon: https://s.juicefs.com/static/jfs/logo.svg
maintainers:
  - email: team@juicedata.io
    name: Juicedata Inc
keywords:
  - juicefs
  - csi
